"""empty message

Revision ID: 01755ddf73d5
Revises: 672d707fc71e
Create Date: 2025-03-28 10:03:41.549295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01755ddf73d5'
down_revision = '672d707fc71e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_custombot', schema=None) as batch_op:
        batch_op.drop_constraint('tbl_custombot_bot_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_custombot', schema=None) as batch_op:
        batch_op.create_unique_constraint('tbl_custombot_bot_name_key', ['bot_name'])

    # ### end Alembic commands ###
