"""empty message

Revision ID: 0843c27469d1
Revises: 494db045fc8f
Create Date: 2025-02-28 11:45:14.171502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0843c27469d1'
down_revision = '494db045fc8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_llm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_llm_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('llm_secret_key', sa.String(length=255), nullable=False))
        batch_op.create_foreign_key(None, 'tbl_basellm', ['base_llm_id'], ['base_llm_id'])
        batch_op.drop_column('provider')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_llm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('llm_secret_key')
        batch_op.drop_column('base_llm_id')

    # ### end Alembic commands ###
