"""empty message

Revision ID: 11bb1ce069d7
Revises: 3e6b9a0e01e5
Create Date: 2025-02-21 16:47:45.758213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11bb1ce069d7'
down_revision = '3e6b9a0e01e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_llm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_llm', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
