"""empty message

Revision ID: 150536ad73f9
Revises: 11bb1ce069d7
Create Date: 2025-02-21 17:04:03.557118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150536ad73f9'
down_revision = '11bb1ce069d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_agents',
    sa.Column('agent_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('agent_description', sa.Text(), nullable=False),
    sa.Column('LLM_Provider', sa.String(length=100), nullable=False),
    sa.Column('LLM_Model', sa.String(length=100), nullable=False),
    sa.Column('agent_role', sa.Text(), nullable=False),
    sa.Column('agent_instructions', sa.Text(), nullable=True),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('Examples', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('del_flg', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tbl_tools.tool_id'], ),
    sa.PrimaryKeyConstraint('agent_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_agents')
    # ### end Alembic commands ###
