"""Add tenant_id to tbl_kb with default

Revision ID: 151da0839a4f
Revises: 9c34e2f0ed21
Create Date: 2025-03-27 12:00:55.089899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '151da0839a4f'
down_revision = '9c34e2f0ed21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_knowledge_base', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False, server_default='11'))
        batch_op.create_foreign_key(None, 'tbl_tenants', ['tenant_id'], ['tenant_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_knowledge_base', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###
