"""Add tenant_id to tbl_agent with default

Revision ID: 25a0d20c5da1
Revises: 151da0839a4f
Create Date: 2025-03-27 12:41:52.205199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25a0d20c5da1'
down_revision = '151da0839a4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False, server_default='5'))
        batch_op.create_foreign_key(None, 'tbl_tenants', ['tenant_id'], ['tenant_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_agents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###
