"""empty message

Revision ID: 2bbc2cb010da
Revises: 5be36a49b58d
Create Date: 2025-02-28 11:00:59.290775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bbc2cb010da'
down_revision = '5be36a49b58d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_basellm',
    sa.Column('base_llm_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('base_provider', sa.String(length=255), nullable=False),
    sa.Column('base_model_name', sa.String(length=255), nullable=False),
    sa.Column('base_model_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('del_flg', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('base_llm_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_basellm')
    # ### end Alembic commands ###
