"""empty message

Revision ID: 494db045fc8f
Revises: 2bbc2cb010da
Create Date: 2025-02-28 11:23:35.668887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '494db045fc8f'
down_revision = '2bbc2cb010da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_basellm', schema=None) as batch_op:
        batch_op.drop_column('base_model_name')
        batch_op.drop_column('base_model_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_basellm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_model_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('base_model_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
