"""empty message

Revision ID: 50a325b2d08d
Revises: 5c9b45ed55e5
Create Date: 2025-03-12 12:48:35.517670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50a325b2d08d'
down_revision = '5c9b45ed55e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_tools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tool_class', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_tools', schema=None) as batch_op:
        batch_op.drop_column('tool_class')

    # ### end Alembic commands ###
