"""empty message

Revision ID: 55d21d0f10e8
Revises: 64737624ced0
Create Date: 2025-03-10 11:05:13.988015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55d21d0f10e8'
down_revision = '64737624ced0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_bot_diagrams',
    sa.Column('diagram_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('diagram_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['tbl_custombot.bot_id'], ),
    sa.PrimaryKeyConstraint('diagram_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_bot_diagrams')
    # ### end Alembic commands ###
