"""Added chathistory relationship to Tenant

Revision ID: 56cacf732702
Revises: 01755ddf73d5
Create Date: 2025-03-31 12:52:50.259537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56cacf732702'
down_revision = '01755ddf73d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_chathistory',
    sa.Column('chathistory_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('response', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tbl_tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('chathistory_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_chathistory')
    # ### end Alembic commands ###
