"""empty message

Revision ID: 5be36a49b58d
Revises: 72cbec98463a
Create Date: 2025-02-24 15:32:55.623452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be36a49b58d'
down_revision = '72cbec98463a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_knowledge_base', schema=None) as batch_op:
        batch_op.alter_column('upload_pdf',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('scrap_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_knowledge_base', schema=None) as batch_op:
        batch_op.alter_column('scrap_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('upload_pdf',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
