"""empty message

Revision ID: 5c86703b2235
Revises: 61a4fd09d492
Create Date: 2025-02-21 10:57:24.013467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c86703b2235'
down_revision = '61a4fd09d492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_custombot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bot_type', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_custombot', schema=None) as batch_op:
        batch_op.drop_column('bot_type')

    # ### end Alembic commands ###
