"""empty message

Revision ID: 64737624ced0
Revises: fac14a58404f
Create Date: 2025-03-08 15:00:27.967666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64737624ced0'
down_revision = 'fac14a58404f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_knowledge_base', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chunk_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('chunk_overlap', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_knowledge_base', schema=None) as batch_op:
        batch_op.drop_column('chunk_overlap')
        batch_op.drop_column('chunk_size')

    # ### end Alembic commands ###
