"""Add tenant_id to tbl_botdiagram with default

Revision ID: 672d707fc71e
Revises: 25a0d20c5da1
Create Date: 2025-03-27 14:12:07.908361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '672d707fc71e'
down_revision = '25a0d20c5da1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_bot_diagrams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False, server_default='5'))
        batch_op.create_foreign_key(None, 'tbl_tenants', ['tenant_id'], ['tenant_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_bot_diagrams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###
