"""empty message

Revision ID: 72cbec98463a
Revises: e17a01e3a6ed
Create Date: 2025-02-21 18:04:55.112577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72cbec98463a'
down_revision = 'e17a01e3a6ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm_provider_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('llm_model_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'tbl_llm', ['llm_model_id'], ['llm_id'])
        batch_op.create_foreign_key(None, 'tbl_llm', ['llm_provider_id'], ['llm_id'])
        batch_op.drop_column('LLM_Model')
        batch_op.drop_column('LLM_Provider')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('LLM_Provider', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('LLM_Model', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('llm_model_id')
        batch_op.drop_column('llm_provider_id')

    # ### end Alembic commands ###
