"""empty message

Revision ID: 90d748e39d26
Revises: 
Create Date: 2025-01-23 16:28:36.649996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90d748e39d26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_custombot', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tbl_tenants', ['tenant_id'], ['tenant_id'])

    with op.batch_alter_table('tbl_error', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tbl_tenants', ['tenant_id'], ['tenant_id'])

    with op.batch_alter_table('tbl_loginuser', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'tbl_tenants', ['tenant_id'], ['tenant_id'])

    with op.batch_alter_table('tbl_tenant_subscriptions', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tbl_tenants', ['tenant_id'], ['tenant_id'])
        batch_op.create_foreign_key(None, 'tbl_bot_plans', ['plan_id'], ['plan_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_tenant_subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('tbl_loginuser', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('tbl_error', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('tbl_custombot', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
