"""empty message

Revision ID: 92da1c0b9538
Revises: fb5978788e95
Create Date: 2025-03-10 12:31:49.420963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92da1c0b9538'
down_revision = 'fb5978788e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_bot_diagrams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bot_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'tbl_custombot', ['bot_id'], ['bot_id'])

    with op.batch_alter_table('tbl_custombot', schema=None) as batch_op:
        batch_op.drop_constraint('tbl_custombot_diagram_id_fkey', type_='foreignkey')
        batch_op.drop_column('diagram_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_custombot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diagram_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('tbl_custombot_diagram_id_fkey', 'tbl_bot_diagrams', ['diagram_id'], ['diagram_id'])

    with op.batch_alter_table('tbl_bot_diagrams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('bot_id')

    # ### end Alembic commands ###
