"""Add tenant_id to tbl_llm with default

Revision ID: 9c34e2f0ed21
Revises: 50a325b2d08d
Create Date: 2025-03-27 11:50:54.132567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c34e2f0ed21'
down_revision = '50a325b2d08d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_llm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False,server_default='11'))
        batch_op.create_foreign_key(None, 'tbl_tenants', ['tenant_id'], ['tenant_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_llm', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###
