"""empty message

Revision ID: 9d2b42e4fa29
Revises: aaf4f7a68d84
Create Date: 2025-02-21 14:58:04.364289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d2b42e4fa29'
down_revision = 'aaf4f7a68d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_tools',
    sa.Column('tool_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('tool_description', sa.Text(), nullable=False),
    sa.Column('tool_logo', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('del_flg', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('tool_id')
    )
    op.drop_table('tbl_Tools')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_Tools',
    sa.Column('tool_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tool_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tool_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tool_logo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('del_flg', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('tool_id', name='tbl_Tools_pkey')
    )
    op.drop_table('tbl_tools')
    # ### end Alembic commands ###
