"""empty message

Revision ID: aaf4f7a68d84
Revises: 5c86703b2235
Create Date: 2025-02-21 14:55:46.103203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf4f7a68d84'
down_revision = '5c86703b2235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_Tools',
    sa.Column('tool_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('tool_description', sa.Text(), nullable=False),
    sa.Column('tool_logo', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('del_flg', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('tool_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_Tools')
    # ### end Alembic commands ###
