"""Fix bot_id column issue

Revision ID: da42392b181d
Revises: 92da1c0b9538
Create Date: 2025-03-10 12:40:02.834905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da42392b181d'
down_revision = '92da1c0b9538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_bot_diagrams', schema=None) as batch_op:
        batch_op.alter_column('bot_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_bot_diagrams', schema=None) as batch_op:
        batch_op.alter_column('bot_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
