"""empty message

Revision ID: e17a01e3a6ed
Revises: 150536ad73f9
Create Date: 2025-02-21 17:27:24.156613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e17a01e3a6ed'
down_revision = '150536ad73f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_llm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_type', sa.String(length=100), nullable=False))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_llm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('model_type')

    # ### end Alembic commands ###
