"""empty message

Revision ID: fac14a58404f
Revises: 0843c27469d1
Create Date: 2025-02-28 14:24:50.803875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fac14a58404f'
down_revision = '0843c27469d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_basellm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_model_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('base_model_type', sa.String(length=100), nullable=False))

    with op.batch_alter_table('tbl_llm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('model_name_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('model_type_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('tbl_llm_base_llm_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tbl_basellm', ['model_type_id'], ['base_llm_id'])
        batch_op.create_foreign_key(None, 'tbl_basellm', ['provider_id'], ['base_llm_id'])
        batch_op.create_foreign_key(None, 'tbl_basellm', ['model_name_id'], ['base_llm_id'])
        batch_op.drop_column('model_name')
        batch_op.drop_column('base_llm_id')
        batch_op.drop_column('model_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_llm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('base_llm_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('model_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tbl_llm_base_llm_id_fkey', 'tbl_basellm', ['base_llm_id'], ['base_llm_id'])
        batch_op.drop_column('model_type_id')
        batch_op.drop_column('model_name_id')
        batch_op.drop_column('provider_id')

    with op.batch_alter_table('tbl_basellm', schema=None) as batch_op:
        batch_op.drop_column('base_model_type')
        batch_op.drop_column('base_model_name')

    # ### end Alembic commands ###
