"""empty message

Revision ID: fb5978788e95
Revises: 55d21d0f10e8
Create Date: 2025-03-10 12:19:43.811185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb5978788e95'
down_revision = '55d21d0f10e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_bot_diagrams', schema=None) as batch_op:
        batch_op.drop_constraint('tbl_bot_diagrams_bot_id_fkey', type_='foreignkey')
        batch_op.drop_column('bot_id')

    with op.batch_alter_table('tbl_custombot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diagram_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tbl_bot_diagrams', ['diagram_id'], ['diagram_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_custombot', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('diagram_id')

    with op.batch_alter_table('tbl_bot_diagrams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bot_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('tbl_bot_diagrams_bot_id_fkey', 'tbl_custombot', ['bot_id'], ['bot_id'])

    # ### end Alembic commands ###
